### ISSUE TITLE
Creating posts checklist

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/DarkSky#12]
- [ ] Create text post
- [ ] text limit
- [ ] Add hastags
- [ ] Add mentions
- [ ] Add hyperlinks
- [ ] Add embeds
- [ ] Add images
- [ ] Add alt text to images
- [ ] Add video
- [ ] Open emoji
- [ ] Add languages
- [ ] post interaction settings
more:
- [ ] create post threads
- [ ] reply to post
- [ ] quote posts

**Comment by FireCubeStudios** [comment]
Might have forgotten some
