### ISSUE TITLE
Viewing posts checklist

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/DarkSky#13]
- [ ] View post text
- [ ] View rich text with facets
- [ ] View link embeds
- [ ] View images
- [ ] View videos
- [ ] View likes
- [ ] View quotes
- [ ] View retweets
- [ ] Like/Unlike
- [ ] Retweet
- [ ] Reply
- [ ] Copy text
- [ ] Copy link
- [ ] View replies

**Comment by FireCubeStudios** [comment]
A lot more of these are done in preview posts
