### ISSUE TITLE
Feature: Support screen readers

### ISSUE THREAD

**Issue by mk-360** [FireCubeStudios/DarkSky#35]
I found the app interesting, so I downloaded it, but it doesn't consider accessibility (A11Y). Specifically, I tried the app with the NVDA screen reader for Windows, and it found unlabeled buttons. When navigating through the posts, it reads strange text instead of the actual post, among other issues.
My test was under Windows 10 pro 22H2 with NonVisual Desktop Access (NVDA) 2024.4.1 (2024.4.1.34550).
Thanks!

**Comment by FireCubeStudios** [comment]
Hello! Since the app is in a "beta" phase where I do a lot of rapid development in a "make fast, break fast" paradigm I have not been focusing on accessibility, performance and quality of life details. However I do want to make accessibility a top priority before the full non-beta official v1 release.

Thank you for opening this issue, I can use it to track progress in making the app more accessible. So far my plans are:

- [ ] High contrast support
- [ ] Screen reader support
- [ ] Keyboard shortcuts and keyboard navigation support
- [ ] Customisations like font sizes
- [ ] Tooltips
- [ ] Text to speech for creating posts

Anyone can suggest more ideas that i might have missed.

**Comment by amadea-system** [comment]
Good support for [https://talonvoice.com/](Talon Voice) would be fantastic!
Just having good keyboard shortcuts & navigation, + exposing the current state of the app through the title would get a good way there.
If you really wanted to go above and beyond, Some sort of RPC API would make this the most voice controllable Bluesky app possible.

**Comment by mk-360** [comment]
Is good to know that you has A11Y on mind. So, consider that in my experience, is easier to code with A11Y at the start, because with other approaches, sometimes, you need to work again in code that is not compatible.

**Comment by Lamparter** [comment]
I think the issue can stay open since it's still relevant.

**Comment by Lamparter** [comment]
Windows Narrator seems to work-ish with DarkSky - however it seems to be reading the .NET class names of the objects that are being interacted with. i.e. pressing on a post makes Narrator read "DarkSky dot Core dot ViewModels dot Temporary dot PostViewModel"
Other parts of the app are narrated correctly though, the navigation view narration works fine, and so does the "Create a new post" dialogue.
